# Generated by Django 3.1.5 on 2021-04-30 04:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postalcode', models.IntegerField(default=0)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Emergency Medicine Specialist', 'Emergency Medicine Specialist'), ('Allergist/Immunologist', 'Allergist/Immunologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Colon and Rectal Surgeon', 'Colon and Rectal Surgeon')], default='Cardiologist', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postalcode', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('diseases', models.CharField(default='somediseases', max_length=2000)),
                ('medicines', models.CharField(default='somemedicines', max_length=2000)),
                ('ts', models.CharField(default='treatments/surgery', max_length=2000)),
                ('status', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientHealth', to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatAdmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitDate', models.DateField()),
                ('description', models.TextField()),
                ('dischargeDate', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorAdmit', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientAdmit', to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('link', models.TextField(null=True)),
                ('calldate', models.DateField(null=True)),
                ('calltime', models.TimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorApp', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientApp', to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postalcode', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
