# Generated by Django 3.1.5 on 2021-04-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patadmit',
            name='roomcharges',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
