# Generated by Django 3.1.5 on 2021-04-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patadmit_roomcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.TextField()),
                ('unitprice', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Admitinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdmitDetails', to='hospital.patadmit')),
            ],
        ),
    ]
