# Generated by Django 3.1.5 on 2021-05-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
    ]
