# Generated by Django 3.1.5 on 2021-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20210501_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patadmit',
            name='dischargeDate',
            field=models.DateField(null=True),
        ),
    ]
