# Generated by Django 3.1.5 on 2021-05-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_appointment_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDate',
        ),
        migrations.CreateModel(
            name='DoctorProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('breakstarttime', models.TimeField(null=True)),
                ('breakendtime', models.TimeField(null=True)),
                ('appfees', models.FloatField()),
                ('admfees', models.FloatField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorProfessional', to='hospital.doctor')),
            ],
        ),
    ]
