# Generated by Django 3.1.5 on 2021-05-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20210502_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofessional',
            name='breakendtime',
        ),
        migrations.RemoveField(
            model_name='doctorprofessional',
            name='breakstarttime',
        ),
        migrations.RemoveField(
            model_name='doctorprofessional',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='doctorprofessional',
            name='starttime',
        ),
        migrations.AddField(
            model_name='doctorprofessional',
            name='totalpat',
            field=models.IntegerField(default=0),
        ),
    ]
