# Generated by Django 3.1.5 on 2021-05-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_remove_admin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='unitprice',
        ),
        migrations.AlterField(
            model_name='charges',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdmitDetails', to='hospital.medicines'),
        ),
    ]
