# Generated by Django 3.1.5 on 2021-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_auto_20210502_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cost', models.FloatField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
