# Generated by Django 3.1.5 on 2021-05-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_operationcosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesApt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('Admitinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AptDetails', to='hospital.patadmit')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AptDetails', to='hospital.medicines')),
            ],
        ),
    ]
