# Generated by Django 3.1.5 on 2021-05-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_chargesapt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesapt',
            name='Admitinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AptDetails', to='hospital.appointment'),
        ),
    ]
