# Generated by Django 3.1.5 on 2021-05-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20210503_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargesapt',
            old_name='Admitinfo',
            new_name='Aptinfo',
        ),
    ]
