# Generated by Django 3.1.5 on 2021-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20210503_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
