# Generated by Django 3.1.5 on 2021-05-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='calldate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='calltime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationcosts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patadmit',
            name='dischargeDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
