# Generated by Django 3.1.5 on 2021-05-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_auto_20210507_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidVaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientVaccination', to='hospital.patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vaccine', to='hospital.medicines')),
            ],
        ),
    ]
